#!/bin/bash


SET_PKG=$(cat ./set-pkg)
TARGET=${1}


## list all targets without dependencies
echo "Make targets:"
make -rpn | sed -n -e '/^$/ { n ; /^[^ .#][^ ]*:/ { s/:.*$// ; p ; } ; }'



if [[ -n $(which checkinstall) ]]  ; then 
    if [[ -n ${1} ]] ; then
        sudo checkinstall -D --install=no --backup=no ${SET_PKG} make ${TARGET}
    fi
else
    echo -e 'Install "checkinstall" first and run again this script'
fi
